spring.application.name=ecommerce-multivendor
server.port=5454

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/abu_ecommerce
spring.datasource.username=root
spring.datasource.password=ROOT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=1234

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abubakerosman56@gmail.com
spring.mail.password=liiukmvogevmlqxm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.jpa.open-in-view=false

# ======================
# Razorpay
# ======================
# Razorpay old payment service
razorpay.api.key=rzp_test_T4MDjSrblCDjRl
razorpay.api.secret=Dj3zRSSWE4Jo6EDYaVDSWfHT


# Razorpay standard checkout
razorpay.key.id=rzp_test_T4MDjSrblCDjRl
razorpay.key.secret=Dj3zRSSWE4Jo6EDYaVDSWfHT